### ISSUE TITLE
KeyError: 'car'

### ISSUE THREAD

**Issue by planckztd** [dongdonghy/repulsion-loss-faster-rcnn-pytorch#1]
```
Traceback (most recent call last):
  File "/home/ztd/Videos/repulsion/repulsion_9_23/train_vgg_repulsion.py", line 207, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
  File "/home/ztd/Videos/repulsion/repulsion_9_23/lib/roi_data_layer/roidb.py", line 122, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/ztd/Videos/repulsion/repulsion_9_23/lib/roi_data_layer/roidb.py", line 119, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/ztd/Videos/repulsion/repulsion_9_23/lib/roi_data_layer/roidb.py", line 103, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/ztd/Videos/repulsion/repulsion_9_23/lib/datasets/imdb.py", line 122, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/ztd/Videos/repulsion/repulsion_9_23/lib/datasets/imdb.py", line 79, in roidb
    self._roidb = self.roidb_handler()
  File "/home/ztd/Videos/repulsion/repulsion_9_23/lib/datasets/pascal_voc.py", line 133, in gt_roidb
    for index in self.image_index]
  File "/home/ztd/Videos/repulsion/repulsion_9_23/lib/datasets/pascal_voc.py", line 266, in _load_pascal_annotation
    cls = self._class_to_ind[obj.find('name').text.lower().strip()]
KeyError: 'car'
```

how to solve with your class from 20 categories to self._classes = ('__background__',  # always index 0
                         'ped','ignore')

You had modified the dataset pascalvoc before?

你是怎么把20类，转变成背景，ped，和ignore，之前就对xml制作的数据进行了修改吗

**Comment by planckztd** [comment]
OK,I have solved this. Using the cityscapes datasets, and transform the data  into pascalvoc type with method author post on Github. I can train with  train_vgg_repulsion.py now.
