### ISSUE TITLE
"IndexError: tuple index out of range" after one iter

### ISSUE THREAD

**Issue by jincheng-hust** [dongdonghy/repulsion-loss-faster-rcnn-pytorch#4]
Hello, thank you for you repo. 
I want to train it on my dataset. After changing some classes things, it run one iter. Then appear IndexError, and I can't trace it with ipdb. Anyone can help? Thanks!
I run it with python2.7, torch0.3.0. Here is the record:

[session 1][epoch  1][iter    0/  97] loss: 2.6290, lr: 1.00e-03
                        rpn_cls: 0.7718, rpn_box: 0.0000, rcnn_cls: 1.3701, rcnn_box: 0.1588, rcnn_repgt: 0.2558, rcnn_repbox: 0.0724
Traceback (most recent call last):
  File "train_vgg_repulsion.py", line 346, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 68, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 78, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
IndexError: tuple index out of range

**Comment by ConanCui** [comment]
Nice problem

**Comment by jincheng-hust** [comment]
> Nice problem

Are you youdu?? I have solve it, spent me several days. But the map is not lager than faster rcnn.

**Comment by XingLiuJia** [comment]
> > Nice problem
> 
> Are you youdu?? I have solve it, spent me several days. But the map is not lager than faster rcnn.

def repulsion(rois, box_deltas, gt_rois, rois_inside_ws, rois_outside_ws):

    deltas = Variable(box_deltas.view(rois.shape[0],256,4))
    rois_inside_ws = Variable(rois_inside_ws.view(rois.shape[0],256,4))                                            
    rois_outside_ws = Variable(rois_outside_ws.view(rois.shape[0],256,4)) 

请问，rois.shape[0],256,4 代表什么意思？我运行程序提示128×256×4 ，我和的512dim 不符合？能解释一下吗？谢谢

**Comment by E-Dreamer-LQ** [comment]
@XingLiuJia 出现同样的问题，请问你解决了吗

**Comment by XingLiuJia** [comment]
> @XingLiuJia 出现同样的问题，请问你解决了吗

这个问题解决了，不过之后出现了另外的问题? 交流加QQ：1195333426
